### ISSUE TITLE
Homepage is affected by dark mode setting

### ISSUE THREAD

**Issue by MoralCode** [Xyfir/ptorx#1]
after creating an account, I enabled the dark mode option and, after logging out, noticed that the homepage has also changed to dark mode

![Screenshot_2019-04-22 Email Forwarding and Aliases by Ptorx](https://user-images.githubusercontent.com/17362949/56513262-c280fe00-64e6-11e9-98da-21254a21a3fa.png)

here's the regular homepage for comparison
![Screenshot_2019-04-23 Email Forwarding and Aliases by Ptorx](https://user-images.githubusercontent.com/17362949/56601212-61712d00-65af-11e9-81c5-d818dd9c801d.png)

I'm fairly sure that the homepage is not intended to be affected by the dark mode setting within the app

**Comment by MrXyfir** [comment]
Hmm. I think I'll leave it, _but_ fix the text colors and also change the purple and blue accents for the entire app to brighter colors that contrast better in dark mode, which is a bit of an issue throughout the entire app.

Should be fixed in the next update.
