### ISSUE TITLE
[QUESTION] Sign DKIM-sig by Ptorx? 

### ISSUE THREAD

**Issue by mzch** [xyfir/ptorx#11]
I sent a test mail and found there is no DKIM signature in the forwarded mail. Doesn't Ptorx sign forwarding mails with DKIM-keys itself?

**Comment by mzch** [comment]
It seems that I misunderstood a bit. Checked `Allow Anonymous Replies`, Ptorx signed correctly. But iCloud service remonstrates against a mismatch between From: header and Envelope-From.

**Comment by MrXyfir** [comment]
Yes, certain mail providers will cause issues because of the mismatch. I believe Ptorx would need to support [ARC](https://en.wikipedia.org/wiki/Authenticated_Received_Chain) to prevent this but it is still experimental.
