### ISSUE TITLE
Android app on F-Droid

### ISSUE THREAD

**Issue by muelli** [xyfir/ptorx#2]
It'd be amazing if the app could be offered via F-Droid, the Free Software app store for Android.

I'd take a stab, but I can't find the code here on Github.

**Comment by MrXyfir** [comment]
I'm not familiar with F-Droid and don't have the time right now to look into it but I'd be happy to point you in the right direction if you'd like to help get it uploaded. What do you need?

Ptorx's mobile code is in the `mobile/` directory. It's essentially just a PhoneGap application wrapping the site. I can get you the APK if that's what needed.

**Comment by MrXyfir** [comment]
Closing this for now. If anyone else wants to work on it I'll reopen.
