### ISSUE TITLE
SSL certificate expired for ptorx.com

### ISSUE THREAD

**Issue by Laiteux** [xyfir/ptorx#5]
NET::ERR_CERT_DATE_INVALID

**Comment by MrXyfir** [comment]
Thanks. Our cron job didn't run.

**Comment by Laiteux** [comment]
Hey, looks like it happened again 😉

**Comment by Laiteux** [comment]
Fixed.

**Comment by MrXyfir** [comment]
❗️Seems the issue was not what I thought it was! Thanks for pointing this out again.

**Comment by Laiteux** [comment]
Ah shit, here we go again

**Comment by MrXyfir** [comment]
Fixed. For now. Who needs functioning cron jobs when you have @Laiteux?

**Comment by Laiteux** [comment]
LMAOOO

**Comment by Laiteux** [comment]
And again

**Comment by MrXyfir** [comment]
Fixed

**Comment by Laiteux** [comment]
I'm happy to see it didn't fail this month. Sent you an email btw 😉

**Comment by MrXyfir** [comment]
Where'd you send it? I'm not seeing anything. My public address contact@xyfir.com gets a load of spam so I disabled forwarding and rarely check it haha but I'm still not seeing anything from you in the past two weeks? Let's try `nomorespam at ptorx.com`. I also have Discord if you want to message me there: xyfir#2299

**Comment by Laiteux** [comment]
Oops, happened again!

**Comment by MrXyfir** [comment]
Back up!

**Comment by Laiteux** [comment]
Hey Xyfir, my Discord somehow got terminated. While I'm working on getting it back, please add me on this one: `M42T#5735`

**Comment by MrXyfir** [comment]
@Laiteux I sent you a friend request yesterday by the way. Add me on whatever account you need xyfir#2299
