### ISSUE TITLE
[HELP] Unable to login (Self Hosted)

### ISSUE THREAD

**Issue by mzch** [xyfir/ptorx#8]
I tried to run Ptorx on my VPS, but can't login. The top screen is as below:

![ScreenShot01](https://user-images.githubusercontent.com/621178/94558322-c3e95500-029a-11eb-9578-c9040d1f00c5.png)

Next, when I clicked `Launch App` button, the white page is loaded:

<img width="1501" alt="ScreenShot02" src="https://user-images.githubusercontent.com/621178/94558452-da8fac00-029a-11eb-9305-0819758ae7ce.png">

Could you tell me how to fix this issue?

EDITED: I cleared my browser histories ,cookies and local storages, but the result is same.

**Comment by MrXyfir** [comment]
It would be helpful if you went into all of the `web/.env` files for Ptorx and its submodules and changed the environment from `"production"` to "development"` so that you can get better error messages. Make sure to rebuild in each web/ directory after!

Have you checked to make sure the API servers are working?

**Comment by mzch** [comment]
I found `Accownt` doesn't listen on port `2074`. I confirmed `PORT = 2074` is in `accuwnt/server/.env`. Why?

Well, I changed `NODE_ENV=develipment` and errors are as below:
<img width="1501" alt="ScreenShot01" src="https://user-images.githubusercontent.com/621178/94581539-2ef45500-02b6-11eb-8dfe-9153c3c5d5ab.png">

<img width="1501" alt="ScreenShot" src="https://user-images.githubusercontent.com/621178/94581590-37e52680-02b6-11eb-89b7-ce79d371f0b3.png">

**Comment by mzch** [comment]
When chaging to `development`, Ptorx showed `Login/Register` button, but `accownt` didn't listen on `2070` so user register failed. And after that it hasn't been shown any more.

In `web/commpoment/info/Info.tsx` I found :
```typescript
interface InfoProps extends WithStyles<typeof styles> {
  user?: Ptorx.User;
}
```
Where is `Ptorx.User` defined and load data?

**Comment by mzch** [comment]
I vist `/accownt/` directly and tried to create my account, Protx said, `Something wrong`.

- log
```
Error: self signed certificate
    at TLSSocket.onConnectSecure (_tls_wrap.js:1501:34)
    at TLSSocket.emit (events.js:315:20)
    at TLSSocket._finishInit (_tls_wrap.js:936:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:710:12)
```

TLS?

**Comment by MrXyfir** [comment]
If I remember correctly, self-signed certificates won't work. I would recommend using https://letsencrypt.org/

The issue is probably that the self-signed certificate is crashing the Accownt server so you cannot sign up or use its API.

**Comment by mzch** [comment]
I run Apache2 as reverse-proxy and got SSL certificate by using Let's Encrypt.
There is no self signed certificate in my VPS.

**Comment by mzch** [comment]
OK, I changed `SMTP_TRANSPORT` from `localhost` to my usual mail server with tls and auth. It fixed.
And I can register my account by visiting `/accownt/` directly, but the same error remains.

**Comment by mzch** [comment]
And then in `/accwnt/` page I tried to login directly but `Not Found` showed.

**Comment by mzch** [comment]
I tried `curl http://127.0.0.1:2070/api/users`
```html
ptorx@de:~$ curl http://127.0.0.1:2070/api/users
<!DOCTYPE html>

<html>
  <head>
    <title>Email Forwarding and Aliases by Ptorx</title>

    <meta
      name="viewport"
      content="minimum-scale=1, initial-scale=1, width=device-width, shrink-to-fit=no"
    />
    <meta http-equiv="content-type" content="text/html; charset=utf-8" />

    <meta
      name="description"
      content="Send and receive mail anonymously with email forwarding and aliases through Ptorx."
    />
    <meta property="og:title" content="Email Forwarding and Aliases by Ptorx" />
    <meta property="og:site_name" content="Ptorx" />
    <meta property="og:url" content="https://ptorx.com" />
    <meta
      property="og:description"
      content="Send and receive mail anonymously with email forwarding and aliases through Ptorx."
    />
    <meta property="og:image" content="https://i.imgur.com/2lemVOD.png" />
    <meta property="og:type" content="website" />

    <link rel="icon" type="image/png" href="/icon.png" />

    <!-- <script src="https://uixmail.com/yalcs//static/yalcs-loader.js" async></script> -->
  </head>
  <body>
    <div id="content"></div>
  <script type="text/javascript" src="/static/main.cf13551286a88786e3dd.js"></script></body>
</html>
```
What's wrong?

**Comment by mzch** [comment]
Hi, fixed this. I use Apache2, changed proxy location `/api` to `/api/6` and went well.
But another problem.

I clicked `Back To...` button then redirect to `/app/jwt=0`, but `Not Found` error.

**Comment by mzch** [comment]
I added Rewrite rule then I can access `/app` and `/info` without problem.
But `Uncaught SyntaxError: Unexpected token '<'` error occurred in main...js.

**Comment by mzch** [comment]
And I use MariaDB but no user data haven't been registered. It it OK?

**Comment by mzch** [comment]
I tried using nginx, said

```
GET https://uixmail.com/accownt/api/account 400
(anonymous) @ main.01bd54664303b3940ef5.js:20
e.exports @ main.01bd54664303b3940ef5.js:20
e.exports @ main.01bd54664303b3940ef5.js:64
Promise.then (async)
u.request @ main.01bd54664303b3940ef5.js:64
r.forEach.u.<computed> @ main.01bd54664303b3940ef5.js:64
(anonymous) @ main.01bd54664303b3940ef5.js:20
componentDidMount @ main.01bd54664303b3940ef5.js:20
ql @ main.01bd54664303b3940ef5.js:36
t.unstable_runWithPriority @ main.01bd54664303b3940ef5.js:44
po @ main.01bd54664303b3940ef5.js:36
$l @ main.01bd54664303b3940ef5.js:36
_l @ main.01bd54664303b3940ef5.js:36
du @ main.01bd54664303b3940ef5.js:36
pu @ main.01bd54664303b3940ef5.js:36
(anonymous) @ main.01bd54664303b3940ef5.js:36
Fl @ main.01bd54664303b3940ef5.js:36
wu @ main.01bd54664303b3940ef5.js:36
render @ main.01bd54664303b3940ef5.js:36
(anonymous) @ main.01bd54664303b3940ef5.js:20
n @ main.01bd54664303b3940ef5.js:1
(anonymous) @ main.01bd54664303b3940ef5.js:1
(anonymous) @ main.01bd54664303b3940ef5.js:1
```

**Comment by mzch** [comment]
It seems that I'm facing another issue. I'm closing this and will open another.
