### ISSUE TITLE
[HELP] Unable to login

### ISSUE THREAD

**Issue by mzch** [xyfir/ptorx#9]
I built Ptorx and run it using nginx and I registered myself and tried to login, but nothing happened.

<img width="1501" alt="ScreenShot" src="https://user-images.githubusercontent.com/621178/94697784-8e646a80-0373-11eb-9c0d-77b022cd3801.png">

1. I clicked `LOGIN/REGISTER` buttn.
2. I entered my credential and clicked `LOGIN` button.
3. Login page was shown again.

**Comment by MrXyfir** [comment]
Did you check the 'Create new account' checkbox? What is the API returning when you try to login?

Can you check the `dir` you set for `STORAGE` (https://github.com/xyfir/accownt/blob/master/types/accownt.d.ts) in Accownt? Are there JSON files in there that contain your user data?

**Comment by mzch** [comment]
1. I created my account successfully.
2. My `.env` is as below:
```sh
PORT=2074

NAME="Ptorx"

JWT_KEY="accownt"

STORAGE={"dir":"/srv/ptorx/accownt-db"}

# NODE_ENV="production"
NODE_ENV="development"

SMTP_MAIL={"from":"no-reply@example.com"}

STATIC_PATH="/accownt/static/"

APP_HOME_URL="https://example.com"

WEB_DIRECTORY="/srv/ptorx/ptorx/accownt/web"

RECAPTCHA_KEY="key"

APP_DELETE_URL="https://example.com/delete?jwt=%JWT%"

SMTP_TRANSPORT={"host":"mx1.mail-services.net","port":587,"auth":{"user":"user@example.com","pass":"password"}}

JWT_EXPIRES_IN="30d"

JWT_COOKIE_NAME="jwt"

ACCOWNT_WEB_URL="https://example.com/accownt"

ACCOWNT_API_URL="https://example.com/accownt/api"

TEMP_JWT_EXPIRES_IN="1h"

EMAIL_VERIFICATION_TEXT_TEMPLATE="/srv/ptorx/templates/verify.txt"

EMAIL_VERIFICATION_HTML_TEMPLATE="/srv/ptorx/templates/verify.html"

PASSWORDLESS_LOGIN_TEXT_TEMPLATE="/srv/ptorx/templates/passwordless.txt"

PASSWORDLESS_LOGIN_HTML_TEMPLATE="/srv/ptorx/templates/passwordless.html"
```
3. Yes, JSON files are created.

**Comment by mzch** [comment]
I tried passwordless login. When clicking the link in the mail, my browser went to:

<img width="1501" alt="ScreenShot01" src="https://user-images.githubusercontent.com/621178/94712524-9082f500-0384-11eb-9aa4-9922455264d7.png">

then I clicked `RETURN TO...`, the browser went to `/app?jwt=0`, but redirected to `/accownt` page immediately.

**Comment by mzch** [comment]
Fixed! Sorry, I forgot to set JWT_KEY in `accownt/server/.env`.
Thanks!
